-
    title: 'Name of the active back-office template'
    description: null
    name: active-admin-template
-
    title: 'Name of the active front-office template'
    description: null
    name: active-front-template
-
    title: 'Name of the active mailing template'
    description: null
    name: active-mail-template
-
    title: 'Name of the active PDF template'
    description: null
    name: active-pdf-template
-
    title: 'Allow negative product stock (1) or not (0)'
    description: null
    name: allow_negative_stock
-
    title: '[Firewall] Number of allowed attemps'
    description: null
    name: allow_slash_ended_uri
-
    title: 'Life time of the cart cookie in the customer browser, in seconds'
    description: null
    name: cart.cookie_lifetime
-
    title: 'Name of the cart cookie'
    description: null
    name: cart.cookie_name
-
    title: 'Use a persistent cookie to keep track of customer cart'
    description: null
    name: cart.use_persistent_cookie
-
    title: 'Check available product stock (1) or ignore it (0) when displaying and changing ordered quantity'
    description: null
    name: check-available-stock
-
    title: 'Show error message instead of a white page on a server error'
    description: null
    name: customer_change_email
-
    title: 'Filename of the error page'
    description: null
    name: customer_confirm_email
-
    title: 'Default available stock when check-available-stock is set to 0.'
    description: null
    name: default_available_stock
-
    title: 'The default quality (in %) of the generated images'
    description: null
    name: default_images_quality_percent
-
    title: 'Ask the customers to confirm their email, 1 for yes, 0 for no'
    description: null
    name: default_lang_without_translation
-
    title: 'Path to the directory where documents are stored'
    description: null
    name: documents_library_path
-
    title: 'The path to the document cache directory in the web space'
    description: null
    name: document_cache_dir_from_web_root
-
    title: 'Allow slash ended uri'
    description: null
    name: error_message.page_name
-
    title: '[Firewall] Activate the firewall'
    description: null
    name: error_message.show
-
    title: '[Firewall/Bruteforce] Number of allowed attemps'
    description: null
    name: form_firewall_active
-
    title: '[Firewall] Time to wait between X attempts'
    description: null
    name: form_firewall_attempts
-
    title: '[Firewall/Bruteforce] Time to wait between X attempts'
    description: null
    name: form_firewall_bruteforce_attempts
-
    title: 'Whitespace trim level of the generated HTML code (0 = none, 1 = medium, 2 = maximum)'
    description: null
    name: html_output_trim_level
-
    title: 'Path to the directory where images are stored'
    description: null
    name: images_library_path
-
    title: 'The path to the image cache directory in the web space'
    description: null
    name: image_cache_dir_from_web_root
-
    title: 'Name of the graphic driver used by the Imagine library (see https://imagine.readthedocs.org)'
    description: null
    name: imagine_graphic_driver
-
    title: 'The ID of the folder containing your information pages : terms, imprint, ...'
    description: null
    name: information_folder_id
-
    title: 'Name of the template view returned when an obsolete (or inactive) product URL is invoked'
    description: null
    name: obsolete_rewriten_url_view
-
    title: 'How document files are delivered in the web space (symlink or copy)'
    description: null
    name: original_document_delivery_mode
-
    title: 'How original (full resolution) images are delivered in the web space (symlink or copy)'
    description: null
    name: original_image_delivery_mode
-
    title: 'File name of the 404 (not found) view in the current template (with extension, e.g. 404.html)'
    description: null
    name: page_not_found_view
-
    title: 'Name of the delivery view in the current PDF template (without extension)'
    description: null
    name: pdf_delivery_file
-
    title: 'Name of the invoice view in the current PDF template (without extension)'
    description: null
    name: pdf_invoice_file
-
    title: 'Compile templates assets automatically upon asset source change (1 = yes, 0 = no)'
    description: null
    name: process_assets
-
    title: 'Enable (1) or disable (0) URL rewriting'
    description: null
    name: rewriting_enable
-
    title: 'Allow customers to change their email. 1 for yes, 0 for no'
    description: null
    name: session_config.default
-
    title: 'Life time of the session cookie in the customer browser, in seconds'
    description: null
    name: session_config.lifetime
-
    title: 'The ID of the ''Terms & Conditions'' content.'
    description: null
    name: terms_conditions_content_id
-
    title: '"Remember me" cookie expiration time, in seconds, for administration users'
    description: null
    name: thelia_admin_remember_me_cookie_expiration
-
    title: '"Remember me" cookie name for administration users'
    description: null
    name: thelia_admin_remember_me_cookie_name
-
    title: '"Remember me" cookie expiration time, in seconds, for customer users'
    description: null
    name: thelia_customer_remember_me_cookie_expiration
-
    title: '"Remember me" cookie name for customer users'
    description: null
    name: thelia_customer_remember_me_cookie_name
-
    title: 'The path (relative to the default back-office template) to the image used when no flag image can be found for a country'
    description: null
    name: unknown-flag-path
-
    title: 'Base URL of the shop (e.g. http://www.yourshopdomain.com)'
    description: null
    name: url_site
-
    title: 'Display and process prices with (0) or without (1) taxes.'
    description: null
    name: use_tax_free_amounts
